# -*- coding: utf-8 -*-
"""whisper-asr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RESYGJBGIo_jwOGq7it1TfLiErJU_1T8
"""

!pip install git+https://github.com/openai/whisper.git
!pip install torchaudio

!pip install whisper torchaudio numpy sounddevice pybind11 noisereduce

!apt-get install portaudio19-dev python-all-dev
!apt-get install python3.10-dev -y

!g++ -std=c++17 main.cpp -o continuous_filtered_asr \
    -I/usr/local/lib/python3.10/dist-packages/pybind11/include \
    -I/usr/include/python3.10 \
    -lpython3.10

!./continuous_filtered_asr

import pybind11

# Print the include path
print(pybind11.get_include())

!python /content/whisper_continuous_with_filter.py

import sounddevice as sd
print(sd.query_devices())

